// Code generated by "stringer -type=KeyID"; DO NOT EDIT.

package she

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SECRET_KEY-0]
	_ = x[MASTER_ECU_KEY-1]
	_ = x[BOOT_MAC_KEY-2]
	_ = x[BOOT_MAC-3]
	_ = x[KEY_1-4]
	_ = x[KEY_2-5]
	_ = x[KEY_3-6]
	_ = x[KEY_4-7]
	_ = x[KEY_5-8]
	_ = x[KEY_6-9]
	_ = x[KEY_7-10]
	_ = x[KEY_8-11]
	_ = x[KEY_9-12]
	_ = x[KEY_10-13]
	_ = x[RAM_KEY-14]
}

const _KeyID_name = "SECRET_KEYMASTER_ECU_KEYBOOT_MAC_KEYBOOT_MACKEY_1KEY_2KEY_3KEY_4KEY_5KEY_6KEY_7KEY_8KEY_9KEY_10RAM_KEY"

var _KeyID_index = [...]uint8{0, 10, 24, 36, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89, 95, 102}

func (i KeyID) String() string {
	if i >= KeyID(len(_KeyID_index)-1) {
		return "KeyID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeyID_name[_KeyID_index[i]:_KeyID_index[i+1]]
}
