linters:
  enable:
    - errorlint
    - unconvert
    - unparam
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - exhaustive
    - exportloopref
    - forcetypeassert
    - goconst
    - gocritic
    - gofmt
    - gosec
    - nilerr
    - usestdlibvars
