name: CI

on:
  push:
    branches: [main]

jobs:

  ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: make build

    - name: Vet
      run: make vet

    - name: Test
      run: make test
