name: CI

on:
  push:
    branches: [main]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: make build

    - name: Vet
      run: make vet

    - name: Test
      run: make test
