name: Linux

on:
  push:
    branches: [main]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x

    - name: Install qemu-user-static
      run: apt-get install -y qemu-user-static

    - name: Disable cgo
      run: go env -w CGO_ENABLED=0

    - name: amd64
      run: GOARCH=amd64 make

    - name: 386
      run: GOARCH=386 make

    - name: arm64
      run: GOARCH=arm64 make
