name: Linux

on:
  push:
    branches: [main]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x

    - name: amd64
      run: CGO_ENABLED=0 GOARCH=amd64 make

    - name: 386
      run: CGO_ENABLED=0 GOARCH=386 make

    - name: arm64
      run: CGO_ENABLED=0 GOARCH=arm64 make
